export type Club = {
  slug: string;
  name: string;
  badge: string;
  primaryColor: string;
  secondaryColor: string;
  tertiaryColor?: string;
};

export const CLUBS: Club[] = [
  {
    slug: "none",
    name: "No club",
    badge: "",
    primaryColor: "#14b8a6",
    secondaryColor: "#0d9488",
  },
  // ── Brazil — Série A ──
  {
    slug: "br2_01",
    name: "Athletico-PR",
    badge: "/clubs/br2_01.png",
    primaryColor: "#af1e2d",
    secondaryColor: "#1a1a1a",
  },
  {
    slug: "br2_02",
    name: "Atlético-MG",
    badge: "/clubs/br2_02.png",
    primaryColor: "#111111",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br2_03",
    name: "Bahia",
    badge: "/clubs/br2_03.png",
    primaryColor: "#0056a8",
    secondaryColor: "#e53935",
    tertiaryColor: "#ffffff",
  },
  {
    slug: "br2_04",
    name: "Botafogo",
    badge: "/clubs/br2_04.png",
    primaryColor: "#1c1c1c",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br2_05",
    name: "RB Bragantino",
    badge: "/clubs/br2_05.png",
    primaryColor: "#d42228",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br2_06",
    name: "Chapecoense",
    badge: "/clubs/br2_06.png",
    primaryColor: "#008744",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br2_07",
    name: "Corinthians",
    badge: "/clubs/br2_07.png",
    primaryColor: "#222222",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br2_08",
    name: "Coritiba",
    badge: "/clubs/br2_08.png",
    primaryColor: "#00703c",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br2_09",
    name: "Cruzeiro",
    badge: "/clubs/br2_09.png",
    primaryColor: "#1a56a5",
    secondaryColor: "#d4a017",
  },
  {
    slug: "br2_10",
    name: "Flamengo",
    badge: "/clubs/br2_10.png",
    primaryColor: "#e41b23",
    secondaryColor: "#1a1a1a",
  },
  {
    slug: "br2_11",
    name: "Fluminense",
    badge: "/clubs/br2_11.png",
    primaryColor: "#9e1a37",
    secondaryColor: "#006b3f",
    tertiaryColor: "#ffffff",
  },
  {
    slug: "br2_12",
    name: "Grêmio",
    badge: "/clubs/br2_12.png",
    primaryColor: "#0d47a1",
    secondaryColor: "#1a1a1a",
    tertiaryColor: "#ffffff",
  },
  {
    slug: "br2_13",
    name: "Internacional",
    badge: "/clubs/br2_13.png",
    primaryColor: "#e30613",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br2_14",
    name: "Mirassol",
    badge: "/clubs/br2_14.png",
    primaryColor: "#2e7d32",
    secondaryColor: "#e0a800",
  },
  {
    slug: "br2_15",
    name: "Palmeiras",
    badge: "/clubs/br2_15.png",
    primaryColor: "#005c29",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br2_16",
    name: "Remo",
    badge: "/clubs/br2_16.png",
    primaryColor: "#003d80",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br2_17",
    name: "Santos",
    badge: "/clubs/br2_17.png",
    primaryColor: "#181818",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br2_18",
    name: "São Paulo",
    badge: "/clubs/br2_18.png",
    primaryColor: "#fc0d1b",
    secondaryColor: "#1a1a1a",
    tertiaryColor: "#ffffff",
  },
  {
    slug: "br2_19",
    name: "Vasco da Gama",
    badge: "/clubs/br2_19.png",
    primaryColor: "#141414",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br2_20",
    name: "Vitória",
    badge: "/clubs/br2_20.png",
    primaryColor: "#b31b1b",
    secondaryColor: "#1a1a1a",
  },
  // ── Brazil — Série B ──
  {
    slug: "br1_01",
    name: "América-MG",
    badge: "/clubs/br1_01.png",
    primaryColor: "#00643b",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br1_02",
    name: "Athletic Club",
    badge: "/clubs/br1_02.png",
    primaryColor: "#2a2a2a",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br1_03",
    name: "Atlético-GO",
    badge: "/clubs/br1_03.png",
    primaryColor: "#d32f2f",
    secondaryColor: "#1a1a1a",
  },
  {
    slug: "br1_04",
    name: "Avaí FC",
    badge: "/clubs/br1_04.png",
    primaryColor: "#1a5fb4",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br1_05",
    name: "Botafogo-SP",
    badge: "/clubs/br1_05.png",
    primaryColor: "#c0392b",
    secondaryColor: "#1a1a1a",
    tertiaryColor: "#ffffff",
  },
  {
    slug: "br1_06",
    name: "Ceará SC",
    badge: "/clubs/br1_06.png",
    primaryColor: "#1e1e1e",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br1_07",
    name: "CRB",
    badge: "/clubs/br1_07.png",
    primaryColor: "#e53935",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br1_08",
    name: "Criciúma EC",
    badge: "/clubs/br1_08.png",
    primaryColor: "#e0a800",
    secondaryColor: "#006b3f",
  },
  {
    slug: "br1_09",
    name: "Cuiabá EC",
    badge: "/clubs/br1_09.png",
    primaryColor: "#1b7340",
    secondaryColor: "#e0a800",
  },
  {
    slug: "br1_10",
    name: "Fortaleza EC",
    badge: "/clubs/br1_10.png",
    primaryColor: "#1258b8",
    secondaryColor: "#e53935",
    tertiaryColor: "#ffffff",
  },
  {
    slug: "br1_11",
    name: "Goiás EC",
    badge: "/clubs/br1_11.png",
    primaryColor: "#006930",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br1_12",
    name: "Juventude",
    badge: "/clubs/br1_12.png",
    primaryColor: "#006040",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br1_13",
    name: "Náutico",
    badge: "/clubs/br1_13.png",
    primaryColor: "#b71c1c",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br1_14",
    name: "Novorizontino",
    badge: "/clubs/br1_14.png",
    primaryColor: "#d4a017",
    secondaryColor: "#1a1a1a",
  },
  {
    slug: "br1_15",
    name: "Londrina EC",
    badge: "/clubs/br1_15.png",
    primaryColor: "#1976d2",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br1_16",
    name: "Operário-PR",
    badge: "/clubs/br1_16.png",
    primaryColor: "#303030",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br1_17",
    name: "Ponte Preta",
    badge: "/clubs/br1_17.png",
    primaryColor: "#262626",
    secondaryColor: "#ffffff",
  },
  {
    slug: "br1_18",
    name: "São Bernardo FC",
    badge: "/clubs/br1_18.png",
    primaryColor: "#c99700",
    secondaryColor: "#1a1a1a",
  },
  {
    slug: "br1_19",
    name: "Sport Recife",
    badge: "/clubs/br1_19.png",
    primaryColor: "#dc143c",
    secondaryColor: "#1a1a1a",
  },
  {
    slug: "br1_20",
    name: "Vila Nova FC",
    badge: "/clubs/br1_20.png",
    primaryColor: "#cc3333",
    secondaryColor: "#ffffff",
  },
  // ── Europe ──
  {
    slug: "eu_01",
    name: "Arsenal",
    badge: "/clubs/eu_01.png",
    primaryColor: "#ef0107",
    secondaryColor: "#ffffff",
  },
  {
    slug: "eu_02",
    name: "Aston Villa",
    badge: "/clubs/eu_02.png",
    primaryColor: "#670e36",
    secondaryColor: "#95bfe5",
  },
  {
    slug: "eu_03",
    name: "Atlético Madrid",
    badge: "/clubs/eu_03.png",
    primaryColor: "#cb3524",
    secondaryColor: "#004d98",
    tertiaryColor: "#ffffff",
  },
  {
    slug: "eu_04",
    name: "FC Barcelona",
    badge: "/clubs/eu_04.png",
    primaryColor: "#004d98",
    secondaryColor: "#a50044",
    tertiaryColor: "#edbb00",
  },
  {
    slug: "eu_05",
    name: "Bayer Leverkusen",
    badge: "/clubs/eu_05.png",
    primaryColor: "#e32221",
    secondaryColor: "#1a1a1a",
  },
  {
    slug: "eu_06",
    name: "Bayern München",
    badge: "/clubs/eu_06.png",
    primaryColor: "#dc052d",
    secondaryColor: "#0066b2",
  },
  {
    slug: "eu_07",
    name: "Borussia Dortmund",
    badge: "/clubs/eu_07.png",
    primaryColor: "#fde100",
    secondaryColor: "#1a1a1a",
  },
  {
    slug: "eu_08",
    name: "Chelsea",
    badge: "/clubs/eu_08.png",
    primaryColor: "#034694",
    secondaryColor: "#ffffff",
  },
  {
    slug: "eu_09",
    name: "Inter Milan",
    badge: "/clubs/eu_09.png",
    primaryColor: "#0068a8",
    secondaryColor: "#1a1a1a",
  },
  {
    slug: "eu_10",
    name: "Juventus",
    badge: "/clubs/eu_10.png",
    primaryColor: "#101010",
    secondaryColor: "#ffffff",
  },
  {
    slug: "eu_11",
    name: "Liverpool",
    badge: "/clubs/eu_11.png",
    primaryColor: "#c8102e",
    secondaryColor: "#ffffff",
  },
  {
    slug: "eu_12",
    name: "Manchester City",
    badge: "/clubs/eu_12.png",
    primaryColor: "#6caddf",
    secondaryColor: "#1c2c5b",
  },
  {
    slug: "eu_13",
    name: "Manchester United",
    badge: "/clubs/eu_13.png",
    primaryColor: "#da291c",
    secondaryColor: "#ffe500",
  },
  {
    slug: "eu_14",
    name: "AC Milan",
    badge: "/clubs/eu_14.png",
    primaryColor: "#fb090b",
    secondaryColor: "#1a1a1a",
    tertiaryColor: "#ffffff",
  },
  {
    slug: "eu_15",
    name: "SSC Napoli",
    badge: "/clubs/eu_15.png",
    primaryColor: "#12a0d7",
    secondaryColor: "#ffffff",
  },
  {
    slug: "eu_16",
    name: "Newcastle United",
    badge: "/clubs/eu_16.png",
    primaryColor: "#241f20",
    secondaryColor: "#ffffff",
  },
  {
    slug: "eu_17",
    name: "Nottingham Forest",
    badge: "/clubs/eu_17.png",
    primaryColor: "#dd0000",
    secondaryColor: "#ffffff",
  },
  {
    slug: "eu_18",
    name: "Paris Saint-Germain",
    badge: "/clubs/eu_18.png",
    primaryColor: "#004170",
    secondaryColor: "#e30613",
  },
  {
    slug: "eu_19",
    name: "Real Madrid",
    badge: "/clubs/eu_19.png",
    primaryColor: "#ffffff",
    secondaryColor: "#febe10",
  },
  {
    slug: "eu_20",
    name: "Tottenham Hotspur",
    badge: "/clubs/eu_20.png",
    primaryColor: "#132257",
    secondaryColor: "#ffffff",
  },
];

export function getClub(slug: string | null | undefined): Club {
  return CLUBS.find((c) => c.slug === slug) ?? CLUBS[0];
}
